language: node_js
node_js:
    - "0.11"
    - "0.10"
before_script:
    - npm install -g grunt-cli
deploy:
    provider: npm
    api_key: 
        secure: g1o64f70D29MjIRz+nwhpcfSC6+g5IpKODcxm3hERFxVLpS3nUihG29M5zqbqJthYfkMtCCNRiFj/khMHELJX5OJMEajdhG9nBD4I3jTwS+P6IOvnhsJnCHo763Kepqcs9MgKiyzFK0/fEUHE93e3/ffIbpJuKdzPfXtKbtQ02g=
    on:
        node: 0.10
        node: 0.11
